### PR TITLE
Update python env and migrate to GitHub Actions

### PR DESCRIPTION
**Pull request by zupo**

### CODE REVIEW

**Comment by zupo** [comment]
Tests pass, but I'm not sure how to add support for multiple Python versions using Nix. 

I could revert back to not using Nix in CI, and going with vanilla Python support in GHA, and using the GHA cache instead of Cachix, but that sounds icky. 

@domenkozar: any ideas?

**Comment by domenkozar** [comment]
https://github.com/cachix/nixpkgs-python

**Comment by zupo** [comment]
> https://github.com/cachix/nixpkgs-python

I don't see how this helps. It's easy to get Python 3.9 into the nix-shell. But then how to tell poetry/pytest to use it.

**Comment by domenkozar** [comment]
You should be able to pass the python to `mkPoetryEnv` using the `python` attribute: https://github.com/nix-community/poetry2nix#mkpoetryenv

**Comment by zupo** [comment]
> You should be able to pass the python to `mkPoetryEnv` using the `python` attribute: https://github.com/nix-community/poetry2nix#mkpoetryenv

Yeah but I can only do this once, right? I cannot have three separate poetry envs with different python versions.

**Comment by zupo** [comment]
Maybe I don't need them in parallel though, good point.

**Comment by zupo** [comment]
All green, ready for review!

**Pull request merged**
